# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(default=0)),
                ('backdrop_path', models.TextField()),
                ('genre', models.TextField()),
                ('tagline', models.TextField()),
                ('status', models.TextField()),
                ('popularity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('vote_average', models.DecimalField(decimal_places=8, max_digits=20)),
                ('production_companies', models.TextField()),
                ('release_date', models.TextField()),
                ('original_title', models.TextField()),
                ('overview', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField()),
                ('typeMovie', models.TextField()),
                ('idx', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCreditsArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(default=0)),
                ('results', models.TextField()),
                ('crew', models.TextField()),
                ('cast', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieCreditsCastArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(default=0)),
                ('results', models.TextField()),
                ('crew', models.TextField()),
                ('cast', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieSimilarArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField()),
                ('typeMovie', models.TextField()),
                ('idx', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PopularPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('also_known_as', models.TextField()),
                ('biography', models.TextField()),
                ('birthday', models.TextField()),
                ('deathday', models.TextField(null=True)),
                ('gender', models.IntegerField()),
                ('idx', models.IntegerField(default=0)),
                ('name', models.TextField()),
                ('place_of_birth', models.TextField()),
                ('popularity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('profile_path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profileimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(default=0)),
                ('profiles', models.TextField()),
            ],
        ),
    ]
